version: '3.8'
services:
  # mariadb:
  #   build: ./requirements/mariadb
  #   image: mariadb
  #   env_file: .env
  #   networks:
  #     - networkHs 
  nginx:
    build: ./requirements/nginx
    image: nginx
    ports: ["5050:80"]
    env_file: .env
    volumes:
      - WordPress:/var/www/html
    networks:
      - networkHs
  wordpress:
    container_name: wp-php
    depends_on:
      - nginx
    build: ./requirements/wordpress
    image: wordpress
    ports: ["9000:9000"]
    env_file: .env 
    volumes:
      - WordPress:/var/www/html
    networks:
      - networkHs

networks:
  networkHs:
    driver: bridge

volumes:
    WordPress:
      driver: local
      driver_opts:
        type: none
        o: bind
        device: /home/hlakhal-/data