version: '3.8'
services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb
    env_file: .env
    volumes:
      - Mariadb:/var/lib/mysql
    networks:
      - networkHs
    restart: always 
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx
    ports: ["443:443"]
    env_file: .env
    depends_on:
      - wordpress
    volumes:
      - WordPress:/var/www/html
    networks:
      - networkHs
    restart: always 
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress
    env_file: .env 
    volumes:
      - WordPress:/var/www/html
    networks:
      - networkHs
    restart: always

networks:
  networkHs:
    driver: bridge

volumes:
    WordPress:
      driver: local
      driver_opts:
        type: bind
        o: bind
        device: /home/hlakhal-/data
    Mariadb:
      driver: local
      driver_opts:
        type: bind
        o: bind
        device: /home/hlakhal-/database