version: '3.8'
services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb
    env_file: .env
    networks:
      - networkHs 
  nginx:
    container_name: nginx_c
    build: ./requirements/nginx
    image: nginx
    ports: ["5050:80"]
    env_file: .env
    depends_on:
      - wordpress
    volumes:
      - WordPress:/var/www/html
    networks:
      - networkHs
  wordpress:
    container_name: wp-php
    build: ./requirements/wordpress
    image: wordpress
    ports: ["9000"]
    env_file: .env 
    volumes:
      - WordPress:/var/www/html
    networks:
      - networkHs

networks:
  networkHs:
    driver: bridge

volumes:
    WordPress:
      driver: local
      driver_opts:
        type: none
        o: bind
        device: /home/hlakhal-/data