version: '3.3'
services:
    mariadb:
      build: ./requirements/mariadb
      image: mariadb
      env_file: .env 
    nginx:
      build: ./requirements/nginx
      image: nginx
      ports: ["5050:80"]
      env_file: .env